// <auto-generated />
namespace MonkeyFist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class takingoffrequiredonhashedpassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(takingoffrequiredonhashedpassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201403190619436_taking off required on hashed password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
